### ISSUE TITLE
DF results approximation from Honeybee plus in Dynamo

### ISSUE THREAD

**Issue by Mahamiho** [ladybug-analysis-tools/honeybee-grasshopper#93]
Hey,
I ran a test simulation using the DF example file, and I noticed that all the results are approximated. Is there a way to change that?
Thanks alot
![image](https://user-images.githubusercontent.com/26859104/44270942-2016c980-a239-11e8-8b0a-273b55c854d2.png)

**Comment by mostaphaRoudsari** [comment]
Yes and I forgot to do it for the Dynamo package. Download the new package which I just pushed a new version which should fix this. Package manager website is down. I hope it has been updated successfully. 

![image](https://user-images.githubusercontent.com/2915573/44277043-6b1fe500-a217-11e8-8db9-ffd0c795bfb0.png)

**Comment by Mahamiho** [comment]
Hey @mostaphaRoudsari ,
The new package is compatible with the latest version of Dynamo, however Dynamo itself in this version is still not very stable and keeps crashing. Can you provide this solution in Honeybee that is compatible with version 1.3?
Thanks alot,

**Comment by mostaphaRoudsari** [comment]
Based on my understanding it should work for both versions. What is the error in version 1.3?

**Comment by Mahamiho** [comment]
Hey @mostaphaRoudsari 
First I get the error in the image, I still install it, but when I try to run the calculation the Generate test point node says Honeybee is not installed. I was trying with Dynamo version 1.3.2.2480
![image](https://user-images.githubusercontent.com/26859104/44392715-1fc94780-a533-11e8-91f0-93679686a335.png)

Thanks for your help in advance,
